// Draft data for the 2025 March Madness Player Pool
// 11 owners, snake draft format
// Team names are best-guess assignments; the app displays ESPN-sourced teams when available

export const owners = [
  {
    name: "McDaniel",
    players: [
      { name: "Mark Sears", pick: 4, team: "Alabama" },
      { name: "Otega Oweh", pick: 19, team: "Kentucky" },
      { name: "Derik Queen", pick: 26, team: "Maryland" },
      { name: "Darrion Williams", pick: 41, team: "Texas Tech" },
      { name: "Chase Hunter", pick: 48, team: "Clemson" },
      { name: "Sean Pedulla", pick: 63, team: "Clemson" },
      { name: "Jackson Shelstad", pick: 70, team: "Oregon" },
      { name: "Chucky Hepburn", pick: 85, team: "Louisville" },
      { name: "John Poulakidas", pick: 92, team: "Northwestern" },
      { name: "Jeremiah Fears", pick: 107, team: "Oklahoma" },
      { name: "David Joplin", pick: 114, team: "Wisconsin" },
    ],
  },
  {
    name: "Schutt",
    players: [
      { name: "Cooper Flagg", pick: 2, team: "Duke" },
      { name: "Jase Richardson", pick: 21, team: "Michigan State" },
      { name: "Jordan Gainey", pick: 24, team: "Tennessee" },
      { name: "Labaron Philon", pick: 43, team: "Alabama" },
      { name: "Koby Brea", pick: 46, team: "Kentucky" },
      { name: "Khaman Maluach", pick: 65, team: "Duke" },
      { name: "Tre Holloman", pick: 68, team: "Michigan State" },
      { name: "Will Riley", pick: 87, team: "Illinois" },
      { name: "Augustas Marciulionis", pick: 90, team: "Kansas" },
      { name: "Kylan Boswell", pick: 109, team: "Arizona" },
      { name: "Jacob Ognacevic", pick: 112, team: "Oakland" },
    ],
  },
  {
    name: "Jeremy",
    players: [
      { name: "L.J. Cryer", pick: 5, team: "Houston" },
      { name: "Miles Kelly", pick: 18, team: "Auburn" },
      { name: "Jaden Akins", pick: 27, team: "Michigan State" },
      { name: "Richie Saunders", pick: 40, team: "Kentucky" },
      { name: "Bennett Stirtz", pick: 49, team: "Drake" },
      { name: "Liam McNeeley", pick: 62, team: "UConn" },
      { name: "Grant Nelson", pick: 71, team: "Alabama" },
      { name: "Daniel Abreu", pick: 93, team: "High Point" },
      { name: "Solo Ball", pick: 106, team: "USC" },
      { name: "Norchad Omier", pick: 128, team: "Baylor" },
    ],
  },
  {
    name: "Wojo",
    players: [
      { name: "Chaz Lanier", pick: 8, team: "Tennessee" },
      { name: "John Tonje", pick: 15, team: "Wisconsin" },
      { name: "Trey Kaufman-Renn", pick: 30, team: "Purdue" },
      { name: "Thomas Haugh", pick: 37, team: "Houston" },
      { name: "Kam Jones", pick: 52, team: "Marquette" },
      { name: "Kasparas Jakucionis", pick: 59, team: "Illinois" },
      { name: "Chris Youngblood", pick: 74, team: "Clemson" },
      { name: "Danny Wolf", pick: 81, team: "Michigan" },
      { name: "Jaxon Kohler", pick: 103, team: "Michigan State" },
      { name: "Alex Karaban", pick: 118, team: "UConn" },
    ],
  },
  {
    name: "Blake",
    players: [
      { name: "Walter Clayton Jr.", pick: 3, team: "Florida" },
      { name: "Zakai Zeigler", pick: 20, team: "Tennessee" },
      { name: "Caleb Love", pick: 25, team: "Arizona" },
      { name: "Wade Taylor IV", pick: 42, team: "Texas A&M" },
      { name: "Fletcher Loyer", pick: 47, team: "Purdue" },
      { name: "Donovan Dent", pick: 69, team: "Arizona" },
      { name: "Tamin Lipsey", pick: 86, team: "Iowa State" },
      { name: "Terrence Edwards Jr.", pick: 108, team: "VCU" },
      { name: "Steven Ashworth", pick: 113, team: "Creighton" },
    ],
  },
  {
    name: "Lee",
    players: [
      { name: "Alijah Martin", pick: 6, team: "Florida" },
      { name: "Curtis Jones", pick: 17, team: "Iowa State" },
      { name: "Tahaad Pettiford", pick: 28, team: "Auburn" },
      { name: "Braden Smith", pick: 39, team: "Purdue" },
      { name: "Lamont Butler", pick: 50, team: "Kentucky" },
      { name: "Chaney Johnson", pick: 72, team: "Auburn" },
      { name: "Denzel Aberdeen", pick: 83, team: "Florida" },
      { name: "Ryan Kalkbrenner", pick: 61, team: "Gonzaga" },
      { name: "Asa Newell", pick: 116, team: "Georgia" },
      { name: "Jason Edwards", pick: 94, team: "Georgia" },
      { name: "Tre Donaldson", pick: 127, team: "Auburn" },
    ],
  },
  {
    name: "Zach",
    players: [
      { name: "Johni Broome", pick: 1, team: "Auburn" },
      { name: "Milos Uzan", pick: 22, team: "Florida" },
      { name: "Alex Condon", pick: 23, team: "Florida" },
      { name: "Rodney Rice", pick: 45, team: "Gonzaga" },
      { name: "Joshua Jefferson", pick: 44, team: "Purdue" },
      { name: "Andrew Carr", pick: 67, team: "Clemson" },
      { name: "Nique Clifford", pick: 66, team: "Colorado State" },
      { name: "Josh Hubbard", pick: 89, team: "Mississippi State" },
      { name: "Zeke Mayo", pick: 88, team: "Kansas" },
      { name: "Khalif Battle", pick: 110, team: "Louisville" },
      { name: "Nick Townsend", pick: 132, team: "South Carolina" },
    ],
  },
  {
    name: "Koehler",
    players: [
      { name: "Kon Knueppel", pick: 7, team: "Duke" },
      { name: "Emanuel Sharp", pick: 16, team: "Houston" },
      { name: "Denver Jones", pick: 29, team: "Auburn" },
      { name: "PJ Haggerty", pick: 38, team: "Memphis" },
      { name: "Jaden Bradley", pick: 51, team: "Alabama" },
      { name: "Deivon Smith", pick: 60, team: "Cincinnati" },
      { name: "Igor Milicic Jr.", pick: 82, team: "Marquette" },
      { name: "RJ Davis", pick: 95, team: "UNC" },
      { name: "Tyler Bilodeau", pick: 104, team: "Alabama" },
      { name: "Nolan Hickman", pick: 117, team: "Gonzaga" },
      { name: "Tre White", pick: 126, team: "VCU" },
    ],
  },
  {
    name: "Webb",
    players: [
      { name: "RJ Luis Jr.", pick: 9, team: "St. John's" },
      { name: "Zuby Ejiofor", pick: 14, team: "Baylor" },
      { name: "John Blackwell", pick: 31, team: "Wisconsin" },
      { name: "Aden Holloway", pick: 36, team: "Alabama" },
      { name: "Julian Reese", pick: 53, team: "Maryland" },
      { name: "Vladislav Goldin", pick: 58, team: "Michigan" },
      { name: "Amari Williams", pick: 75, team: "Kentucky" },
      { name: "Nate Bittle", pick: 80, team: "Oregon" },
      { name: "Tomislav Ivisic", pick: 102, team: "Baylor" },
      { name: "Matthew Murrell", pick: 119, team: "Memphis" },
    ],
  },
  {
    name: "Myers",
    players: [
      { name: "Will Richard", pick: 10, team: "Florida" },
      { name: "Tyrese Proctor", pick: 13, team: "Duke" },
      { name: "J'Wan Roberts", pick: 32, team: "Houston" },
      { name: "Kadary Richmond", pick: 35, team: "St. John's" },
      { name: "Milan Momcilovic", pick: 54, team: "Iowa State" },
      { name: "Christian Anderson", pick: 57, team: "Utah" },
      { name: "Selton Miguel", pick: 76, team: "Kansas State" },
      { name: "KJ Lewis", pick: 79, team: "Arizona" },
      { name: "Zeb Jackson", pick: 123, team: "Virginia Tech" },
    ],
  },
  {
    name: "Kevin",
    players: [
      { name: "Chad Baker-Mazara", pick: 11, team: "Auburn" },
      { name: "JT Toppin", pick: 12, team: "Texas Tech" },
      { name: "Ja'Kobi Gillespie", pick: 34, team: "Auburn" },
      { name: "Sion James", pick: 55, team: "Auburn" },
      { name: "Graham Ike", pick: 78, team: "Gonzaga" },
      { name: "Dain Dainja", pick: 77, team: "Baylor" },
      { name: "Tyler McGhie", pick: 121, team: "Bucknell" },
    ],
  },
];

// Flat list of all players with owner reference for easy lookup
export const allPlayers = owners.flatMap((owner) =>
  owner.players.map((player) => ({ ...player, owner: owner.name }))
);
