// Draft data for the 2026 March Madness Player Pool
// 12 owners, 10-round snake draft (120 total picks)
// Imported from manual draft spreadsheet

export const owners = [
  {
    name: "Lee",
    players: [
      { name: "Cameron Boozer", pick: 1, team: "Duke" },
      { name: "Boogie Fland", pick: 24, team: "Florida" },
      { name: "Patrick Ngongba II", pick: 25, team: "Duke" },
      { name: "Motiejus Krivas", pick: 48, team: "Arizona" },
      { name: "Braylon Mullins", pick: 49, team: "UConn" },
      { name: "Coen Carr", pick: 72, team: "Michigan State" },
      { name: "Tyon Grant-Foster", pick: 73, team: "Gonzaga" },
      { name: "Chance Mallory", pick: 96, team: "Virginia" },
      { name: "Braden Frager", pick: 97, team: "Nebraska" },
      { name: "Ian Jackson", pick: 120, team: "St. John's" },
    ],
  },
  {
    name: "Wojo",
    players: [
      { name: "Thomas Haugh", pick: 2, team: "Florida" },
      { name: "Tarris Reed Jr.", pick: 23, team: "UConn" },
      { name: "Nick Boyd", pick: 26, team: "Wisconsin" },
      { name: "Ja'Kobi Gillespie", pick: 47, team: "Tennessee" },
      { name: "Malik Reneau", pick: 50, team: "Miami" },
      { name: "Tobe Awaka", pick: 71, team: "Arizona" },
      { name: "Sam Lewis", pick: 74, team: "Virginia" },
      { name: "Tomislav Ivisic", pick: 95, team: "Illinois" },
      { name: "MJ Collins Jr.", pick: 98, team: "Utah State" },
      { name: "Devin Royal", pick: 119, team: "Ohio State" },
    ],
  },
  {
    name: "Koehler",
    players: [
      { name: "Brayden Burries", pick: 3, team: "Arizona" },
      { name: "Aday Mara", pick: 22, team: "Michigan" },
      { name: "Pryce Sandfort", pick: 27, team: "Nebraska" },
      { name: "Kylan Boswell", pick: 46, team: "Illinois" },
      { name: "Ryan Conwell", pick: 51, team: "Louisville" },
      { name: "Oscar Cluff", pick: 70, team: "Purdue" },
      { name: "Urban Klavzar", pick: 75, team: "Florida" },
      { name: "Killyan Toure", pick: 94, team: "Iowa State" },
      { name: "Seth Trimble", pick: 99, team: "North Carolina" },
      { name: "Aiden Sherrell", pick: 118, team: "Alabama" },
    ],
  },
  {
    name: "Webb",
    players: [
      { name: "Koa Peat", pick: 4, team: "Arizona" },
      { name: "Solo Ball", pick: 21, team: "UConn" },
      { name: "Darryn Peterson", pick: 28, team: "Kansas" },
      { name: "Andrej Stojakovic", pick: 45, team: "Illinois" },
      { name: "Duke Miles", pick: 52, team: "Vanderbilt" },
      { name: "Donovan Atwell", pick: 69, team: "Texas Tech" },
      { name: "Otega Oweh", pick: 76, team: "Kentucky" },
      { name: "Lejuan Watts", pick: 93, team: "Texas Tech" },
      { name: "Jeremiah Wilkinson", pick: 100, team: "Georgia" },
      { name: "Jayden Stone", pick: 117, team: "Missouri" },
    ],
  },
  {
    name: "Sam",
    players: [
      { name: "Yaxel Lendeborg", pick: 5, team: "Michigan" },
      { name: "Fletcher Loyer", pick: 20, team: "Purdue" },
      { name: "Milos Uzan", pick: 29, team: "Houston" },
      { name: "Alex Karaban", pick: 44, team: "UConn" },
      { name: "Nate Ament", pick: 53, team: "Tennessee" },
      { name: "Rienk Mast", pick: 68, team: "Nebraska" },
      { name: "Dame Sarr", pick: 77, team: "Duke" },
      { name: "Nolan Winter", pick: 92, team: "Wisconsin" },
      { name: "Tavari Johnson", pick: 101, team: "Akron" },
      { name: "Dailyn Swain", pick: 116, team: "Texas" },
    ],
  },
  {
    name: "Kevin",
    players: [
      { name: "Isaiah Evans", pick: 6, team: "Duke" },
      { name: "Braden Smith", pick: 19, team: "Purdue" },
      { name: "Thijs De Ridder", pick: 30, team: "Virginia" },
      { name: "Meleek Thomas", pick: 43, team: "Arkansas" },
      { name: "Zuby Ejiofor", pick: 54, team: "St. John's" },
      { name: "Malik Thomas", pick: 67, team: "Virginia" },
      { name: "Bruce Thornton", pick: 78, team: "Ohio State" },
      { name: "Amari Allen", pick: 91, team: "Alabama" },
      { name: "Devin McGlockton", pick: 102, team: "Vanderbilt" },
      { name: "Mario Saint-Supery", pick: 115, team: "Gonzaga" },
    ],
  },
  {
    name: "McPeppers",
    players: [
      { name: "Milan Momcilovic", pick: 7, team: "Iowa State" },
      { name: "Labaron Philon Jr.", pick: 18, team: "Alabama" },
      { name: "Jeremy Fears Jr.", pick: 31, team: "Michigan State" },
      { name: "Tyler Tanner", pick: 42, team: "Vanderbilt" },
      { name: "Silas Demary Jr.", pick: 55, team: "UConn" },
      { name: "Paulius Murauskas", pick: 66, team: "St. Mary's" },
      { name: "Trevon Brazile", pick: 79, team: "Arkansas" },
      { name: "Oziyah Sellers", pick: 90, team: "St. John's" },
      { name: "Shelton Henderson", pick: 103, team: "Miami" },
      { name: "Eian Elmer", pick: 114, team: "Miami (OH)" },
    ],
  },
  {
    name: "Jeremy",
    players: [
      { name: "Alex Condon", pick: 8, team: "Florida" },
      { name: "AJ Dybantsa", pick: 17, team: "BYU" },
      { name: "Christian Anderson", pick: 32, team: "Texas Tech" },
      { name: "Tre White", pick: 41, team: "Kansas" },
      { name: "Robert Wright III", pick: 56, team: "BYU" },
      { name: "Henri Veesaar", pick: 65, team: "North Carolina" },
      { name: "Anthony Dell'Orso", pick: 80, team: "Arizona" },
      { name: "Carson Cooper", pick: 89, team: "Michigan State" },
      { name: "Nimari Burnett", pick: 104, team: "Michigan" },
      { name: "John Mobley Jr.", pick: 113, team: "Ohio State" },
    ],
  },
  {
    name: "Blake",
    players: [
      { name: "Darius Acuff Jr.", pick: 9, team: "Arkansas" },
      { name: "Graham Ike", pick: 16, team: "Gonzaga" },
      { name: "Tamin Lipsey", pick: 33, team: "Iowa State" },
      { name: "Rueben Chinyelu", pick: 40, team: "Florida" },
      { name: "Cayden Boozer", pick: 57, team: "Duke" },
      { name: "Jaxon Kohler", pick: 64, team: "Michigan State" },
      { name: "Trey McKenney", pick: 81, team: "Michigan" },
      { name: "Chris Cenac Jr.", pick: 88, team: "Houston" },
      { name: "Mark Mitchell", pick: 105, team: "Missouri" },
      { name: "Dominique Daniels Jr.", pick: 112, team: "Cal Baptist" },
    ],
  },
  {
    name: "Hartman",
    players: [
      { name: "Joshua Jefferson", pick: 10, team: "Iowa State" },
      { name: "Emanuel Sharp", pick: 15, team: "Houston" },
      { name: "Trey Kaufman-Renn", pick: 34, team: "Purdue" },
      { name: "Ivan Kharchenkov", pick: 39, team: "Arizona" },
      { name: "Blake Buchanan", pick: 58, team: "Iowa State" },
      { name: "Tyler Nickel", pick: 63, team: "Vanderbilt" },
      { name: "Joseph Tugler", pick: 82, team: "Houston" },
      { name: "Nikolas Khamenia", pick: 87, team: "Duke" },
      { name: "Donovan Dent", pick: 106, team: "UCLA" },
      { name: "C.J. Cox", pick: 111, team: "Purdue" },
    ],
  },
  {
    name: "Zach",
    players: [
      { name: "Kingston Flemings", pick: 11, team: "Houston" },
      { name: "Jaden Bradley", pick: 14, team: "Arizona" },
      { name: "Xaivian Lee", pick: 35, team: "Florida" },
      { name: "John Blackwell", pick: 38, team: "Wisconsin" },
      { name: "Latrell Wrightsell", pick: 59, team: "Alabama" },
      { name: "Melvin Council Jr.", pick: 62, team: "Kansas" },
      { name: "Flory Bidunga", pick: 83, team: "Kansas" },
      { name: "Billy Richmond III", pick: 86, team: "Arkansas" },
      { name: "Wes Enis", pick: 107, team: "South Florida" },
      { name: "Rashaun Agee", pick: 110, team: "Texas A&M" },
    ],
  },
  {
    name: "Schutt",
    players: [
      { name: "Keaton Wagler", pick: 12, team: "Illinois" },
      { name: "Morez Johnson Jr.", pick: 13, team: "Michigan" },
      { name: "Elliot Cadeau", pick: 36, team: "Michigan" },
      { name: "David Mirkovic", pick: 37, team: "Illinois" },
      { name: "Tyler Bilodeau", pick: 60, team: "UCLA" },
      { name: "Bryce Hopkins", pick: 61, team: "St. John's" },
      { name: "Bennett Stirtz", pick: 84, team: "Iowa" },
      { name: "Tre Donaldson", pick: 85, team: "Miami" },
      { name: "Trent Perry", pick: 108, team: "UCLA" },
      { name: "Mikey Lewis", pick: 109, team: "St. Mary's" },
    ],
  },
];

// Flat list of all players with owner reference for easy lookup
export const allPlayers = owners.flatMap((owner) =>
  owner.players.map((player) => ({ ...player, owner: owner.name }))
);
